### ISSUE TITLE
Porting Catchall

### ISSUE THREAD

**Issue by jaden-young** [DigitalG/NWR#8]
Maintaining a checklist here of files that exist in the old repo that don't exist in this repo. Starting with lua files, maybe including others if we find them. Trying to resolve them one by one to see which are dead, which can just be copied over (maybe with a new `.d.ts`), which are incompatible and would require implementation in TS, etc.

### Scripts

- [x] settings.lua
- [x] rescale.lua
- [x] addon_init.lua - just imports components/internal/client_utils.lua. Source of the missing `FindTalentValue()` errors
- [x] aitest.lua - empty, don't need
- [x] events.lua
- [x] gamemode.lua (kind-of)
- [x] items.lua
- [x] popups.lua
- [x] settings_old.lua - old, don't need
- [x] utilities.lua - used by custom items, tableContains used by cheats, getIndex used by abilities,
- [x] components/
  - [x] demo/
    - [x]  events.lua
    - [x] init.lua
  - [x] voicelines/
    - [x] voicelines.lua
    - [x] keyvalues/
- [x] internal/
  - [x] client_util.lua
  - [x] events.lua
  - [x] eventtest.lua - used to print all event data. Relies on util.lua
  - [x] gamemode.lua
  - [x] util.lua
- [x] items/ (a lot here)
- [x] libraries
  - [x] adv_log.lua
  - [x] animations.lua - not used anywhere, doesn't override anything. Exclude for now.
  - [x] better_cooldown.lua
  - [x] keyvalues.lua
  - [x] notifications.lua - only used in demo
  - [x] physics.lua - included the file, TODO type annotations... someday if we use it from TS. That thing is huge.
  - [x] popups.lua  
  - [x] projectiles.lua - not used
  - [x] tempTable.lua - not used anywhere, exclude
  - [x] utils.lua - not used, exclude. Contains valve code to deep print a table, but there's already a global `DeepPrintTable` func by default, plus the `internal/util` has a `PrintTable` func
  - [x] vanilla_extensions.lua - Some extensions to BaseNPC and BaseAbility. Implicitly relies on additions to `GameMode` made in keyvalues.lua
- [x] modifiers/
  - [x] modifier_anko_senei_ta_jashu_slow.lua
  - [x] modifier_courier_speed.lua - requires settings.lua
  - [x] modifier_custom_mechanics.lua
  - [x] modifier_generic_custom_indicator.lua
  - [x] modifier_global_boost.lua - requires settings.lua
  - [x] modifier_neji_internal_bleeding.lua - huskar overrides, disregard
  - [x] modifier_responses.lua - works with voicelines.lua
  - [x] talents.lua - empty. Auto talents seem to work without it, exclude for now.
- [x] music.lua 
- [x] cheats.lua
- [x] label.lua
- [x] leaverGold.lua - dead code - isn't referenced anywhere. It defines a `GameMode:ModifyGoldGainDC`, but that isn't referenced in the old repo anywhere, and a search of moddota lua api comes up empty.

### Models

- [x] buildings, though towers are still vanilla

**Comment by DigitalG** [comment]
Commenting here to see if webhook can parse this
